# Generated by Django 4.2.16 on 2026-03-15 02:58

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=snippets.models.generate_ref_code, max_length=20, unique=True),
        ),
    ]
