# Generated by Django 4.2.16 on 2026-02-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
