# Generated by Django 4.2.16 on 2026-03-15 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
