# Generated by Django 4.2.16 on 2026-03-07 13:07

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_coachmission_alter_snippet_created_by_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmessage',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
