# Generated by Django 4.2.16 on 2026-03-16 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_profile_ai_count_aichatlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='xp',
        ),
    ]
