# Generated by Django 4.2.16 on 2026-02-28 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_status', models.CharField(max_length=20)),
                ('q2_time', models.CharField(max_length=20)),
                ('q3_strength', models.CharField(max_length=20)),
                ('q4_risk', models.CharField(max_length=20)),
                ('q5_goal', models.CharField(max_length=20)),
                ('result_type', models.CharField(choices=[('stable', '安定型（制作代行）'), ('influence', '影響力型（コンテンツ）'), ('attack', '攻撃型（物販）'), ('build', '構築型（SaaS/ツール）')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
