# Generated by Django 4.2.16 on 2026-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_remove_profile_ai_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_count',
            field=models.IntegerField(default=0),
        ),
    ]
