# Generated by Django 4.2.16 on 2026-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcheckin',
            name='last_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachcheckin',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
