# Generated by Django 4.2.16 on 2026-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_profile_ai_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_last_used',
            field=models.DateField(blank=True, null=True),
        ),
    ]
