# Generated by Django 4.2.16 on 2026-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_profile_ai_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
