# Generated by Django 4.2.16 on 2026-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_remove_coachcheckin_streak_remove_profile_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='streak',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
