# Generated by Django 4.2.16 on 2026-03-08 14:05

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_remove_profile_streak_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(default=None, max_length=12, unique=True),
        ),
    ]
