# Generated by Django 4.2.16 on 2026-03-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachcheckin',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
