# Generated by Django 4.2.16 on 2026-03-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_profile_last_login_date_profile_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
