# Generated by Django 4.2.16 on 2026-03-10 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0012_coachcheckin_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='referral_rewarded',
            new_name='is_premium',
        ),
        migrations.AlterUniqueTogether(
            name='coachcheckin',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coachmission',
            name='day',
        ),
        migrations.RemoveField(
            model_name='coachmission',
            name='xp_reward',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q1_status',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q2_time',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q3_strength',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q4_risk',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q5_goal',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_bonus_days',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_until',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_end',
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coachcheckin',
            name='checked_in_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coachmessage',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coachmission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='result_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='DailyProgress',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='Roadmap',
        ),
        migrations.RemoveField(
            model_name='coachcheckin',
            name='last_checkin',
        ),
        migrations.RemoveField(
            model_name='coachcheckin',
            name='points',
        ),
        migrations.RemoveField(
            model_name='coachcheckin',
            name='streak',
        ),
    ]
