# Generated by Django 4.2.16 on 2026-03-18 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_profile_streak_freeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ai_last_used',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_token',
        ),
    ]
