# Generated by Django 4.2.16 on 2026-03-10 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_remove_referral_referred_remove_referral_referrer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='coachmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachmission',
            name='xp_reward',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CoachCheckin',
        ),
        migrations.DeleteModel(
            name='CoachMessage',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
