# Generated by Django 4.2.16 on 2026-03-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_remove_profile_ai_last_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
