# Generated by Django 4.2.16 on 2026-03-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_communitypost_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
