# Generated by Django 4.2.16 on 2026-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0015_diagnosisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
