# Generated by Django 4.2.16 on 2026-03-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0017_aichathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
