# Generated by Django 4.2.16 on 2026-03-22 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0018_mission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
