# Generated by Django 4.2.16 on 2026-03-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0019_usermission_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('seller', 'SELLER'), ('build', 'BUILD'), ('influence', 'INFLUENCE'), ('stable', 'STABLE')], default='seller', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sidejob_type',
            field=models.CharField(blank=True, default='seller', max_length=20),
        ),
    ]
