# Generated by Django 4.2.16 on 2026-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0024_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='q5',
        ),
    ]
