# Generated by Django 4.2.16 on 2026-03-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0026_aisearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sidejob', models.CharField(max_length=200)),
                ('income', models.IntegerField()),
                ('story', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sidejob',
            old_name='reward',
            new_name='difficulty',
        ),
        migrations.AddField(
            model_name='sidejob',
            name='income_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidejob',
            name='income_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
