# Generated by Django 4.2.16 on 2026-03-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0027_successstory_rename_reward_sidejob_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidejob',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sidejob',
            name='income_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sidejob',
            name='income_min',
            field=models.IntegerField(default=0),
        ),
    ]
