# Generated by Django 4.2.16 on 2026-03-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0028_alter_sidejob_difficulty_alter_sidejob_income_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidejob',
            name='difficulty',
            field=models.IntegerField(),
        ),
    ]
